.PHONY: all clean

PRJ_DIR = $(CURDIR)
export PRJ_DIR

ROOT_DIR = $(CURDIR)/../..
export ROOT_DIR

APP_DIR = $(PRJ_DIR)/cpp-app
export APP_DIR

export COMPILER=g++

subdirs = cpp-app main

include $(ROOT_DIR)/make/make.subdirs
